steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/helloserver:$TAG_NAME', '.']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'helloserver', 
           '--image=us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/helloserver:$TAG_NAME', 
           '--region', 'us-central1', '--platform', 'managed']
